[snowflake]
account = "<Snowflake Account>"
user = "<User Name>"
password = "<Password>"
role = "TELCO_NETWORK_OPTIMIZATION_ANALYST"
warehouse = "TELCO_NETWORK_OPTIMIZATION_ANALYST_WH"
database = "TELCO_NETWORK_OPTIMIZATION_PROD"
schema = "RAW"
